server:
  
    port: 8088
    context-path: /base/
    #session:
    #  timeout: 60
    #tomcat:
     # max-threads: 800
     # uri-encoding: UTF-8
      
    
#应用名称  
appName: app1
#应用实体类所在的位置
entityLocation: com.iscas.quickframe.domain.s

#cas配置
casConfig:
  #cas服务器地址信息
  #casPrefix: https://124.16.136.144:8543/cas
  casPrefix: http://172.16.10.156:8081/cas
  #应用服务器对外发布地址
  shiroPrefix: http://172.16.10.156:8088/base
  #本地登录地址（控制器requestMapping地址）
  localLoginURI: /toLogin
  #shiro session超时时间(分钟)
  shiroSessionTimeout: 90
  #无效session清除定时器间隔(分钟)
  sessionValidationInterval: 20
  #redis存储session时间(分钟)
  redisSessionStoreTime: 90
  #权限缓存时间(分钟)
  permissionCacheTime: 80
  
  
#log
logging.config: classpath:logback.xml  

  
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.hbm2ddl.auto: update
spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.format_sql: true
spring.jackson.serialization.indent_output: true

# REDIS (RedisProperties)
#spring.redis.database=
spring.redis.host: 127.0.0.1
spring.redis.password: 123456
spring.redis.port: 6379 
spring.redis.pool.max-idle: 100 
spring.redis.pool.min-idle: 1
spring.redis.pool.max-active: 1000
spring.redis.pool.max-wait: -1

#upload file
multipart.maxFileSize: 20MB
multipart.maxRequestSize: 20MB
spring:
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: true
  
      
---
spring: 
  profiles: dev
  datasource:
    #权限数据库配置
    permission:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/testshiro
      username: bNVOqb7WKLX5Bjnw+LMv92taj25KOxDimXxILPQjw42wgv+1lHzOH8kr97xDwWdhpY67QuYCS7sWN4W46YbkFA== 
      password: bNVOqb7WKLX5Bjnw+LMv92taj25KOxDimXxILPQjw42wgv+1lHzOH8kr97xDwWdhpY67QuYCS7sWN4W46YbkFA== 
      #password: lNW86aJhyGeKSP8+ZJLuUR6nCGZjPLEzEudapBC8VOT5PCE7Pt3A4XLfg8QzXI2uhjR+9VU4Rin6U0VIyeCgNg== 
       # 使用druid数据源
     
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小 
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
     
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
    #应用服务器配置  
    app:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/testshiro
      username: bNVOqb7WKLX5Bjnw+LMv92taj25KOxDimXxILPQjw42wgv+1lHzOH8kr97xDwWdhpY67QuYCS7sWN4W46YbkFA== 
      password: bNVOqb7WKLX5Bjnw+LMv92taj25KOxDimXxILPQjw42wgv+1lHzOH8kr97xDwWdhpY67QuYCS7sWN4W46YbkFA== 
      #password: lNW86aJhyGeKSP8+ZJLuUR6nCGZjPLEzEudapBC8VOT5PCE7Pt3A4XLfg8QzXI2uhjR+9VU4Rin6U0VIyeCgNg== 
       # 使用druid数据源
     
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小 
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
     
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true

---
  
spring: 
  profiles: prod
  datasource:
    permission:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/boot
      username: root
      password: root
     
      
    app:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test
      username: root
      password: 12345  


  
 
 